version: "3"

services:
  python-server:
    image: fastapi:py37
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 8080:80

    working_dir: /workspace
    volumes:
      - ./:/workspace

    restart: always
    depends_on:
     - mysql-db


  mysql-db:
    image: mysql:8
    platform: linux/x86_64
    volumes:
      - data:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=1234


volumes:
  data:
